### ISSUE TITLE
Add ability to specify classes, functions e.t.c. without namespace

### ISSUE THREAD

**Issue by Nikita-GkmSoft** [PetrPPetrov/beautiful-capi#60]
Currently it is not possible to create included xml specification to specify members of an existing namespace. This means that a namespace must be fully specified in a single file.
Also the issue is preventing creation of files with parts of namespaces shared between different projects.

**Comment by RudenkoSergej** [comment]
closed by commit 1474f3d7c7de6499027e87794fec1995a0f88326
